title: DarrenC Knowledge wiki
lang: en
description: A collection of everything I like to know about

remote_theme: rundocs/jekyll-rtd-theme

addons_branch: true
edit: true

addons:
  - github
  - i18n
  - plugins
  - analytics

copyright:
  revision: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions